### ISSUE TITLE
‘node --harmony’: No such file or directory

### ISSUE THREAD

**Issue by mwamodojnr** [usebedrock/bedrock-cli#7]
I get the ```/usr/bin/env: ‘node --harmony’: No such file or directory``` error and I have to hunt down bedrock to change the shebang. I don't know if am the only one with this issue.

**Comment by mwamodojnr** [comment]
When I run ```bedrock init``` or ```bedrock init bootstrap4```

**Comment by Wolfr** [comment]
If you type `node -v` what kind of output do you get?

**Comment by mwamodojnr** [comment]
my node version is ```v10.7.0```
