### ISSUE TITLE
Remove SSH usage?

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock-cli#9]
Is there a reason to use SSH? This can lead to people being asked about their SSH keychain etc..

Can't we clone via HTTPS when upgrading?

Using:

    git clone https://github.com/usebedrock/bedrock.git

<img width="903" alt="screenshot 2019-02-21 at 12 05 10" src="https://user-images.githubusercontent.com/12690/53178954-1fe5f500-35f3-11e9-9ff5-a09ea540967d.png">

**Comment by xavez** [comment]
Good point, I see no reason why we can't.
